
version: 2

models:
  - name: stg_sn__postcodes
    description: "A staging table containing subnational postcode data"
    columns:
      - name: "Postcode 1"
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null