select
  "Postcode 1"
  ,"Postcode 2"
  ,"Postcode 3"
  ,"Date Introduced"
  ,"User Type"
  ,"Easting"
  ,"Northing"
  ,"Positional Quality"
  ,"County Code"
  ,"County Name"
  ,"Local Authority Code"
  ,"Local Authority Name"
  ,"Ward Code"
  ,"Ward Name"
  ,"Country Code"
  ,"Country Name"
  ,"Region Code"
  ,"Region Name"
  ,"Parliamentary Constituency Code"
  ,"Parliamentary Constituency Name"
  ,"European Electoral Region Code"
  ,"European Electoral Region Name"
  ,"Primary Care Trust Code"
  ,"Primary Care Trust Name"
  ,"Lower Super Output Area Code"
  ,"Lower Super Output Area Name"
  ,"Middle Super Output Area Code"
  ,"Middle Super Output Area Name"
  ,"Output Area Classification Code"
  ,"Output Area Classification Name"
  ,"Longitude"
  ,"Latitude"
  ,"Spatial Accuracy"
  ,"Last Uploaded"
  ,"Location"
  ,"Socrata ID"
from
  {{source('sn', 'national_statistics_postcode_lookup_uk')}}